name: Build and push Docker

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker default meta
        id: meta-default
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository }}
          flavor: |
            latest=true
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Docker custom meta
        id: meta-custom
        uses: docker/metadata-action@v4
        with:
          images: |
            docker.io/${{ github.repository }}
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}-custom
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build and push default image
        uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ steps.meta-default.outputs.tags }}
          labels: ${{ steps.meta-default.outputs.labels }}
          file: Dockerfile
      - name: Build and push custom image
        uses: docker/build-push-action@v3
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ steps.meta-custom.outputs.tags }}
          labels: ${{ steps.meta-custom.outputs.labels }}
          file: Dockerfile_custom
